name: build paper

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc pandoc-citeproc texlive librsvg2-bin

    - name: Build paper
      run: |
        pandoc --from=markdown --to=latex --template=template.latex --output=whitepaper.pdf paper.md

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: whitepaper
        path: whitepaper.pdf